### ISSUE TITLE
incorrect check for replicaSet

### ISSUE THREAD

**Issue by cikin** [nightw/mikoomi-zabbix-mongodb-monitoring#14]
https://github.com/nightw/mikoomi-zabbix-mongodb-monitoring/blob/master/mikoomi-mongodb-plugin.php#L443

the condition should be `if (!($rs_status['ok']))`

**Comment by nightw** [comment]
@cikin Are you sure that this is true for all MongoDB versions? On which version is it bad specifically? I've just merged a pull request which uses separate directories for different MongoDB versions. Could you please send a pull request for the right ones to fix this bug? Thank you.

**Comment by cikin** [comment]
Hi @nightw ,
I don't think it's related to the Mongodb version. The idea is that you can execute rs.status() against all mongo components (stand-alone/config/mongos/rs members) and rs.status() output won't be null/0 never. You have to rely on the actual return code.

Here's an example

```
#config server
configsvr> rs.status()
{ "info" : "configsvr", "ok" : 0, "errmsg" : "not running with --replSet" }
configsvr> db.adminCommand({replSetGetStatus:1})
{ "info" : "configsvr", "ok" : 0, "errmsg" : "not running with --replSet" }

#mongos
mongos> rs.status()
{
	"info" : "mongos",
	"ok" : 0,
	"errmsg" : "replSetGetStatus is not supported through mongos"
}
# standalone
> rs.status()
{ "ok" : 0, "errmsg" : "not running with --replSet" }
> 
#rs member
ReplSet1:PRIMARY> rs.status()
{
	"set" : "ReplSet1",
	"date" : ISODate("2016-06-15T16:40:13Z"),
	"myState" : 1,
	"members" : [
		{
			"_id" : 0,
			"name" : "localhost:30001",
			"health" : 1,
			"state" : 1,
			"stateStr" : "PRIMARY",
			"uptime" : 26250,
			"optime" : Timestamp(1464886954, 3),
			"optimeDate" : ISODate("2016-06-02T17:02:34Z"),
			"electionTime" : Timestamp(1465982567, 1),
			"electionDate" : ISODate("2016-06-15T09:22:47Z"),
			"self" : true
		}
	],
	"ok" : 1
}

```

Hope this explains it.

Thanks!

**Comment by cikin** [comment]
As a side note: I was testing on MongoDB 2.6

**Comment by nightw** [comment]
@cikin Thank you, I see the point now. Could you please send a small pull request changing this line in all 3 files/versions of the script? (Sorry for the duplicate work, I plan to do a rework, which makes the 3 Zabbix/MongoDB version monitoring script to be one file again)

**Comment by cikin** [comment]
@nightw Done.

**Comment by nightw** [comment]
@cikin I've merged it. Thank you for the fix.
