### ISSUE TITLE
Dependency

### ISSUE THREAD

**Issue by hayou** [nightw/mikoomi-zabbix-mongodb-monitoring#18]
Hello,

You also need this package : openssl-devel .
Regards

**Comment by nightw** [comment]
Hi,

After some thought given to it I would not add this to the README as a requirement for multiple reasons:
- It's only needed when you want to connect to MongoDB via an SSL connection (which is an option, but disabled by default), so a lot of people will not need SSL libraries when using this tool
- Even if you use SSL, then the PHP PECL MongoDB extension will need SSL support and It can be solved via multiple ways, which does not invole installing a specific SSL library (e.g. statically linked extension built by compiling your own from source on an another machine)
- Even if you would use your Linux distribution's package management, then it would either use OpenSSL packages (different names for different distributions in many cases, so `openssl-devel` is just one alternativa) or maybe use LibreSSL ones, so the name cannot be well documented

I close this issue now, but if you think there is a good way to include this part to the README.md then please reopen with a suggestion. Thanks.

Best regards,
Pal David Gergely
