### ISSUE TITLE
replication lag 

### ISSUE THREAD

**Issue by isaidashev** [nightw/mikoomi-zabbix-mongodb-monitoring#22]
How I can monitoring replication lag?

**Comment by nightw** [comment]
The code already collects the replication lag if the node is a member of a replicaset and it is not the primary. The collected metric is called `repl_member_replication_lag_sec`.

It should work automatically but if you think it does not show up, then you can check the code around [this line](https://github.com/nightw/mikoomi-zabbix-mongodb-monitoring/blob/master/mongodb-3.2/mikoomi-mongodb-plugin-32.php#L492) to see if there is a problem for you.

I am closing this issue with this answer. If you think you still have further questions then please reply and reopen it. Thanks.
