### ISSUE TITLE
Issue with .php

### ISSUE THREAD

**Issue by bradenwright** [nightw/mikoomi-zabbix-mongodb-monitoring#4]
So I'd really like to get this working, been using mongodb and zabbix for a little while so seems like a good combo.  Thanks for keeping up with this project!

Anyways I don't know very much about php.... but I'm getting the following error:

<code>PHP Parse error:  syntax error, unexpected '[' in /etc/zabbix/externalscripts/mikoomi-mongodb-plugin.php on line 30
0</code>

The line is:
<code>
$options = getopt("Dh:p:z:u:x:H:P:", ["ssl"]) ;
</code>
I tried removing the ssl portion or using a script from the git history from before ssl support was added.  When I do this the script runs (via /etc/zabbix/externalscripts/mikoomi-mongodb-plugin.sh -z dev-db1.example.com) but I don't get any data on the zabbix server.

I tried to check /tmp/mikoomi-mongodb-plugin.php_*.log but nothing is being written in the log or data file.

I'm running on ubuntu 12.04, PHP 5.3.10-1ubuntu3.16 with Suhosin-Patch (cli) (built: Feb 13 2015 20:15:04).  Any help on tracking down the issue would be appreciated

**Comment by nightw** [comment]
Thank you for the report, you're right. I've met this problem too but was too lazy to fix it upstream. :) The script uses the newer array syntax only available in PHP 5.4. Now I've changed it to be backward compatible which should work now on Ubuntu 12.04 too. I've fixed it #5 which is now merged to master. Please comment whether it worked or not. Thanks.

**Comment by bradenwright** [comment]
FYI that fix did work to get the script running so thanks for the quick reply.  Also I went ahead and looked up how to upgrade to newer php.  

I'm having some issue not getting data, but I want to retest a few things before I post further on that.

**Comment by nightw** [comment]
Ok, thanks for the reply. I'll close this issue now as it's resolved. If you find something else then please open a separate issue for that. Thanks.
