### ISSUE TITLE
Can't import the Template on Zabbix 3.0.1

### ISSUE THREAD

**Issue by Caddi1971** [nightw/mikoomi-zabbix-mongodb-monitoring#9]
Import of the original XML File:
Import failed
Details
Invalid XML tag "/zabbix_export": unexpected tag "time".

If i correct this, then i get the next error with proxy_hostid

I hope you can help me. :)

**Comment by nightw** [comment]
Hi @Caddi1971

I've never tested these templates on Zabbix 3.x, so it is quite possible that they do not work.

I think this is part of the reason why @Elbandi proposed this pull request #8. Which is in progress (with some Hungarian talks at the end, sorry).

If you think you can help with that work I would appreciate it. Or you may want to wait for @Elbandi, because currently I don't have enough time to test the whole thing on Zabbix 3.0, since I do not use Zabbix at the moment at my current workplace.

**Comment by nightw** [comment]
Hi @Caddi1971

The mentioned pull request is merged. You should try the same file names again (the old code got moved to separate files suffixed with `-24`. Now it should work with Zabbix 3.0.

**Comment by nightw** [comment]
Sorry, I was mistaken in the previous comment. The new modifications are in fact in the files ending in `-24` suffix and they're for the 2.4 version, not for the 3.0. The original files remained unchanged, so they are for version `2.2.x` still. So you should try the files with the `-24` suffix and hope that they will work for 3.0. Sorry, there is no real support for 3.0 yet.

**Comment by rzippert** [comment]
Just reporting that the 2.4 template does import fine on Zabbix 3.0.1-1 right now. Still have to test if the monitoring does work too, but I don't know of a reason for it not to.

**Comment by nightw** [comment]
Thank you for the information @rzippert. That's very good news. If it really works well then could you report it again please? In that case I would close this issue.

**Comment by rzippert** [comment]
I'll be activating the monitoring on my servers in the next few days. I'll let you know.

**Comment by yngvith** [comment]
Thanks a lot for your good work guys ;-)  Have you already configured the mikoomi-mongodb-plugin.php for the new mongodb 1.1 driver and MongoDB version 3.2 ?.

**Comment by Caddi1971** [comment]
I've take the new Scripts and it works fine.
Thanks for the good work.

**Comment by rzippert** [comment]
It's working fine for me too. If I find something wrong I'll let you know!

Thanks for your work =)

**Comment by vadimprt** [comment]
hi,

i have being testing this template on newest zabbix server with proxy servers in amazon,
i imported template to zabbix every thing is fine now i installed all dependence packages on mongo server tested .php and .sh script with all parameters with proxy server in this region getting successful connection message with 0 result and no data coming to zabbix server (host is monitored via proxy) 

have any one configured this one and can help me?

thank in advance.

**Comment by nightw** [comment]
@vadimprt  Actually I am not sure that anybody has already used these templates and scripts successfully with Zabbix 3.2 yet. So it may not work for some changes in Zabbix.

May want to debug the script a bit with the `-D` option. And see the data file in `/tmp` and try sending it yourself to Zabbix. For example a missing value (only key but no data in the data file) can cause this.

Sorry, I have no good ideas about these type of errors. I also had them back when I used this monitoring pack, but they were for a lot of different reasons and I don't remember exactly.

**Comment by yngvith** [comment]
I've successfully implemented those scripts on Zabbix 2.4 as well as Zabbix 3.0.1.
Thanks a lot for your good work :-)

**Comment by nightw** [comment]
The thanks goes to @Elbandi mostly. :) But I think I will close the issue now, since most of the problems seems to be solved and this one is already too long. Please open a new one if someone has any more problems.
